app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

from django.contrib.auth import views as auth_views
import notifications.urls

from users.views import *

urlpatterns = [
	path('admin/', admin.site.urls),
	path('logout/', auth_views.LogoutView.as_view(), name='logout'),
	re_path('^inbox/notifications/', include(notifications.urls, namespace='notifications')),

	path('', index, name='index'),
	path('about/', about, name='about'),
	# path('check-online/', check_online, name='check_online'),

	path('users/', include('users.urls')),
	path('chats/', include('chats.urls')),
	]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chats/urls.py
from django.urls import path

from chats.views import *

app_name = 'chats'

urlpatterns = [
	path('', chats_view, name='chat_list'),
	path('<uuid:chat_uuid>/', chats_view, name='chat_detail'),
	path('create-chat/', ChatCreateView.as_view(), name='create_chat'),
	path('<uuid:chat_uuid>/delete_chat/', ChatDeleteView.as_view(), name='delete_chat'),
	]

users/urls.py
from django.urls import path

from users.views import *

app_name = 'users'

urlpatterns = [
	path('registration/', UserRegistrationView.as_view(), name='register'),
	path('login/', UserLoginView.as_view(), name='login'),
	path('profile/<int:user_id>/', user_profile_view, name='profile'),
	path('edit-profile/<int:user_id>/', edit_profile, name='edit-profile'),
	# path('upload-post/<int:user_id>/', upload_post, name='upload-post'),
	]

users/models.py
import os

import uuid
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_resized import ResizedImageField
from phonenumber_field.modelfields import PhoneNumberField


def validate_file_size(value):
	filesize = value.size
	max_size = 10 * 1024 * 1024  # 10 МБ
	if filesize > max_size:
		raise ValidationError("Размер файла превышает максимально допустимый размер (10 МБ).")


def get_user_image_path(instance, filename):
	return os.path.join('users', 'images', 'user_profile_images', str(instance.user.id),
	                    str(uuid.uuid4()) + '.' + filename.split('.')[-1])


def get_post_image_path(instance, filename):
	return os.path.join('users', 'images', 'user_post_images', str(instance.user.id), str(uuid.uuid4()))


class CustomUserManager(BaseUserManager):
	def create_user(self, email, password=None, **extra_fields):
		if not email:
			raise ValueError(_('Электронная почта обязательна'))
		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, password=None, **extra_fields):
		extra_fields.setdefault('is_staff', True)
		extra_fields.setdefault('is_superuser', True)
		return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(
		max_length=255,
		unique=True,
		verbose_name=_('Электронная почта')
		)
	first_name = models.CharField(
		max_length=30,
		verbose_name=_('Имя')
		)
	last_name = models.CharField(
		max_length=30,
		verbose_name=_('Фамилия')
		)
	phone_number = PhoneNumberField(
		unique=True,
		null=True,
		blank=True,
		verbose_name=_('Номер телефона'),
		)
	is_active = models.BooleanField(
		default=True
		)
	is_staff = models.BooleanField(
		default=False
		)
	user_permissions = models.ManyToManyField(
		'auth.Permission',
		blank=True,
		verbose_name=_('Права пользователя'),
		related_name='customuser_permissions',
		)
	objects = CustomUserManager()
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['first_name', 'last_name']

	class Meta:
		verbose_name = _('Пользователь')
		verbose_name_plural = _('Пользователи')

	def __str__(self):
		return f'{self.email} | {self.get_full_name()}'

	def get_full_name(self):
		full_name = f'{self.first_name} {self.last_name}'
		return full_name.strip()


class UserProfile(models.Model):
	user = models.OneToOneField(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		related_name='user_profile',
		)
	username = models.CharField(
		max_length=40,
		unique=True,
		blank=True,
		null=True,
		verbose_name=_('Имя пользователя'),
		)
	profile_image = ResizedImageField(
		size=[1024, 1024],
		crop=['middle', 'center'],
		upload_to=get_user_image_path,
		default='/users/images/user_profile_images/default_user_avatar.jpg',
		blank=True,
		verbose_name=_('Фотография'),
		validators=[FileExtensionValidator('JPEG JPG PNG SVG'.split()), validate_file_size],
		)
	age = models.PositiveSmallIntegerField(
		null=True,
		blank=True,
		verbose_name=_('Возраст'),
		)
	biography = models.TextField(
		max_length=500,
		blank=True,
		null=True,
		verbose_name=_('Биография'),
		)
	city = models.CharField(
		blank=True,
		null=True,
		verbose_name=_('Город'),
		max_length=168,
		)

	class Meta:
		verbose_name = _('Профиль пользователя')
		verbose_name_plural = _('Профили пользователей')

	def __str__(self):
		return self.user.email


class ConnectionHistory(models.Model):
	user = models.OneToOneField(
		CustomUser,
		on_delete=models.CASCADE,
		related_name='connection_history'
		)
	device_id = models.UUIDField(
		default=uuid.uuid4,
		editable=False,
		verbose_name=_('id устройства')
		)
	date_joined = models.DateField(
		auto_now_add=True,
		verbose_name=_('Дата регистрации')
		)
	last_online = models.DateTimeField(
		auto_now=True,
		null=True,
		blank=True,
		verbose_name=_('Время последнего входа')
		)
	online_status = models.BooleanField(
		default=False
		)

	class Meta:
		verbose_name = _('История подключений')
		verbose_name_plural = _('Истории подключений')

	def __str__(self):
		return self.user.email

	def update_online_status(self, online_status: bool):
		self.online_status = online_status
		self.last_online = timezone.now()
		self.save(update_fields=['online_status', 'last_online'])


class Post(models.Model):
	user = models.ForeignKey(
		CustomUser,
		on_delete=models.CASCADE,
		related_name='user_posts',
		verbose_name=_('Создатель поста'),
		)
	text = models.CharField(
		max_length=100,
		blank=True,
		null=True,
		verbose_name=_('Текст поста'),
		)
	image = models.ImageField(
		upload_to=get_post_image_path,
		blank=True,
		null=True,
		verbose_name=_('Изображение поста'),
		)
	created = models.DateTimeField(
		auto_now_add=True,
		verbose_name=_('Время создания'),
		)

	class Meta:
		ordering = ['-created']
		verbose_name = _('Пост')
		verbose_name_plural = _('Посты')

	def __str__(self):
		return f'{self.id}'

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from phonenumber_field.formfields import PhoneNumberField

from users.models import UserProfile, Post

User = get_user_model()


class UserRegistrationForm(UserCreationForm):
	email = forms.EmailField()
	password1 = forms.CharField(widget=forms.PasswordInput)
	password2 = forms.CharField(widget=forms.PasswordInput)
	first_name = forms.RegexField(regex=r'^[a-zA-Zа-яА-Я]', max_length=30)
	last_name = forms.RegexField(regex=r'^[a-zA-Zа-яА-Я]', max_length=30)

	class Meta:
		model = User
		fields = ('email', 'password1', 'password2', 'first_name', 'last_name')

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise ValidationError(_('Пароли не совпадают'))
		return password2


class LoginForm(AuthenticationForm):
	username = forms.CharField(widget=forms.EmailInput({'required': '', 'name': '', 'type': 'text'}))
	password = forms.CharField(
		widget=forms.PasswordInput({'required': '', 'name': '', 'type': 'password', 'autocomplete': 'new-password'}))


class UserProfileForm(forms.ModelForm):
	username = forms.CharField(max_length=50, required=False)
	profile_image = forms.ImageField(required=False, label=_('Фотография'))
	biography = forms.CharField(widget=forms.Textarea, required=False, label=_('Биография'))
	phone_number = PhoneNumberField(required=True, label=_('Номер телефона'))
	city = forms.CharField(required=False, label=_('Город'))
	country = forms.CharField(required=False, label=_('Страна'))

	class Meta:
		model = UserProfile
		fields = ('profile_image', 'biography', 'phone_number', 'city', 'country')


class MessageForm(forms.Form):
	text = forms.CharField(label=_('Текст сообщение'), widget=forms.Textarea())


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['text', 'image']
		labels = {
			'text': '',
			'image': '',
			}
		widgets = {
			'text': forms.Textarea(attrs={
				'id': 'create-post__input-text',
				'placeholder': 'Текст поста',
				'rows': '1',
				}),
			'image': forms.FileInput(attrs={
				'id': 'create-post__select-image',
				'style': 'display: none',
				}),
			}

	def clean(self):
		text = self.cleaned_data.get('text')
		image = self.cleaned_data.get('image')

		if not text and not image:
			raise ValidationError(_('Пост не может быть пустым'))

		return self.cleaned_data


class EditProfileForm(forms.ModelForm):
	first_name = forms.CharField(max_length=30)
	last_name = forms.CharField(max_length=30)

	class Meta:
		model = UserProfile
		fields = ('first_name', 'last_name', 'profile_image', 'biography', 'username', 'age', 'city')

users/views.py
from django.contrib.auth import login, get_user_model
from django.contrib.auth.views import LoginView
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import UserRegistrationForm, LoginForm, PostForm, EditProfileForm

User = get_user_model()


def about(request):
	return render(request, 'users/about.html')


def index(request):
	return render(request, 'users/index.html')


# def user_register(request):
# 	if request.method.lower() == 'post':
# 		form = RegisterForm(request.POST)
# 		if form.is_valid():
# 			user = form.save()
# 			UserProfile.objects.create(user=user)
# 			login(request, user)
# 			messages.success(request, 'Регистрация прошла успешно!')
# 			return redirect('index')
# 	else:
# 		form = RegisterForm()
# 	return render(request, 'users/register.html', {'form': form})

class UserRegistrationView(CreateView):
	template_name = 'users/register.html'
	form_class = UserRegistrationForm
	success_url = reverse_lazy('index')

	def form_valid(self, form):
		response = super().form_valid(form)
		login(self.request, self.object)

		return response


class UserLoginView(LoginView):
	template_name = 'users/login.html'
	form_class = LoginForm
	success_url = reverse_lazy('index')

	def form_valid(self, form, *args, **kwargs):
		response = super().form_valid(form)
		response.set_cookie('is_login', 'true')
		return super().form_valid(form)


def user_profile_view(request, user_id):
	user = get_object_or_404(User, id=user_id)

	if request.method == 'POST':
		post_form = PostForm(request.POST, request.FILES)

		if post_form.is_valid():
			post = post_form.save(commit=False)
			post.user = request.user
			post.save()
			return redirect('users:profile', user_id=user_id)
	else:
		post_form = PostForm()

	if request.user.id == user_id:
		user_online = 'online'
	else:
		user_online = is_online if (
			is_online := user.connection_history.online_status) else user.connection_history.last_online

	context = {
		'user_id': user_id,
		'user_full_name': user.get_full_name(),
		'user_profile_image': user.user_profile.profile_image,
		'user_biography': user.user_profile.biography.strip(),
		'user_posts': user.user_posts.all(),
		'user_online': user_online,

		'post_form': post_form,
		}

	return render(request, 'users/user_profile.html', context)


def edit_profile(request, user_id):
	user = get_object_or_404(User, id=user_id)
	user_profile = user.user_profile

	if request.method == 'POST':
		edit_profile_form = EditProfileForm(request.POST, request.FILES, instance=user_profile)

		if edit_profile_form.is_valid():
			edit_profile_form.save()
			return redirect('users:profile', user_id=user_id)
	else:
		edit_profile_form = EditProfileForm(instance=user_profile, initial={
			'first_name': user.first_name,
			'last_name': user.last_name,
			})

	context = {
		'user_id': user_id,
		'edit_profile_form': edit_profile_form,
		}

	return render(request, 'users/edit_profile.html', context)

templates/users/about.html
{% extends 'base.html' %}

{% block content %}
  <h1>Hello</h1>
{% endblock content %}

templates/users/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
  <link rel="stylesheet" href="{% static 'users/css/edit_profile_styles.css' %}">
{% endblock links %}

{% block content %}
  <section id="edit-profile-section" class="col">
    <div class="row flex-column text-center">

      <div class="col">
        <form method="post">
          {% csrf_token %}
          <div id="info-section" class="row align-items-center mx-2 my-4 p-2 text-center">
            <div id="profile-image" class="col-3" style="width: 100px">
              <img src="{{ edit_profile_form.instance.profile_image.url }}" alt="" class="img-fluid rounded-circle">
            </div>

            <div id="user-name" class="col d-flex justify-content-start">
              {{ edit_profile_form.first_name }} {{ edit_profile_form.last_name }}
            </div>
          </div>

          <div id="profile-bio" class="col">
            {{ edit_profile_form.biography }}
          </div>

          <div id="additional-info">
            <div id="profile-username">
              {{ edit_profile_form.username }}
            </div>
            <div id="profile-age">
              {{ edit_profile_form.age }}
            </div>
            <div id="profile-city">
              {{ edit_profile_form.city }}
            </div>
          </div>

          <button type="submit">Сохранить</button>
        </form>
      </div>

    </div>
  </section>
{% endblock %}

templates/users/index.html
{% extends 'base.html' %}

{% block title %}Talker{% endblock title %}

{% block content %}
  <div class="col">
    <h1>Welcome to Talker</h1>
    <a href="{% url 'chats:chat_list' %}">Перейти к чатам</a>
  </div>
{% endblock content %}

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Вход{% endblock title %}

{% block links %}
  <link rel="stylesheet" href="{% static 'users/css/login_styles.css' %}">
{% endblock links %}

{% block end_scripts %}
  <script src="{% static 'users/js/login.js' %}" type="text/javascript"></script>
{% endblock end_scripts %}

{% block content %}
  <div class="login-box">
    <p>Вход в аккаунт</p>
    <form method="post" autocomplete="off">
      {% csrf_token %}
      <div class="user-box">
        {{ form.username }}
        <label>Почта</label>
      </div>
      <div class="user-box">
        {{ form.password }}
        <label>Пароль</label>
      </div>
      <a href="#">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        Войти
      </a>
    </form>
    <p>Нет аккаунта? <a href="{% url 'users:register' %}" class="a2">Зарегистрироваться!</a></p>
  </div>
{% endblock content %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Регистрация{% endblock title %}
{% block links %}
  <link rel="stylesheet" href="{% static 'users/css/register_styles.css' %}">
{% endblock %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <div class="container">
      <div class="card">
        <a class="singup">Регистрация</a>
        <ul>{% for field in form %}
          {% for error in field.errors %}
            <li>{{ field.name }}: {{ error }}</li>
          {% endfor %}
        {% endfor %}</ul>

        <div class="inputBox1">
          {{ form.email }}
          <span class="user">Почта</span>
        </div>

        <div class="inputBox">
          {{ form.password1 }}
          <span>Пароль</span>
        </div>

        <div class="inputBox">
          {{ form.password2 }}
          <span>Еще раз Пароль</span>
        </div>

        <div class="inputBox">
          {{ form.first_name }}
          <span>Имя</span>
        </div>

        <div class="inputBox">
          {{ form.last_name }}
          <span>Фамилия</span>
        </div>

        <button class="enter">Войти</button>
        <p>Или <a href="{% url 'users:login' %}">Войти</a></p>
      </div>
    </div>
  </form>
{% endblock content %}

templates/users/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% load users_custom_filters %}

{% block title %}
  {{ user_full_name }}
{% endblock %}

{% block links %}
  <link rel="stylesheet" href="{% static 'users/css/user_profile_styles.css' %}">
{% endblock links %}

{% block end_scripts %}
  <script src="{% static 'users/js/user_profile.js' %}"></script>
{% endblock end_scripts %}

{% block content %}
  {# Секция профиля пользователя #}
  <section id="profile-section" class="col position-relative">

    <div class="row">
      <div class="col-12 col-lg-8">
        {#  Информационная секция пользователя #}
        <section id="info-section" class="row align-items-center mx-1 mx-md-2 mt-4 p-3 hover-scale">
          {# Фото пользователя #}
          <div id="profile-image" class="col-12 col-sm-3 mx-auto mx-sm-0">
            <img src="{{ user_profile_image.url }}" alt="" class="img-fluid rounded-circle">
          </div>

          {# Имя и онлайн статус пользователя #}
          <div class="col-12 col-sm d-flex justify-content-center justify-content-sm-start">
            <div class="row flex-column">
              <h1 id="name"
                  class="col my-2 my-sm-0 d-flex justify-content-center justify-content-sm-start">{{ user_full_name }}</h1>
              <span id="online-status"
                    class="col-12 col-sm mb-2 d-flex justify-content-center justify-content-sm-start">{{ user_online|last_online_format }}</span>
            </div>
          </div>

          {# Кнопка добавления в друзья или редактирования профиля #}
          <div class="col d-flex justify-content-center justify-content-sm-end">
            {% if request.user.id == user_id %}
              <button class="p-1 profile-button" onclick="location.href='{% url 'users:edit-profile' user_id %}'">
                Редактировать профиль <i class="fa-duotone fa-pen-to-square"></i>
              </button>
            {% else %}
              <a href="#">Заявка в друзья <i class="fa-solid fa-user-group"></i></a>
            {% endif %}
          </div>
        </section>

        {# Биография пользователя #}
        {% if user_biography %}
          <div id="bio" class="row mx-1 mx-md-2 my-3 p-2 hover-scale">
            <p class="col">{{ user_biography }}</p>
          </div>
        {% endif %}
      </div>

      {# Друзья пользователя #}
      <div class="col-12 col-lg-4">
        <section id="friends"
                 class="row flex-column mx-1 mx-md-2 ms-lg-0 me-lg-2 p-2 hover-scale {% if user_biography %}mb-3 mt-lg-4{% else %}my-3 mb-lg-0{% endif %}">
          <header id="friend-section-title" class="col">
            <h4>Друзья:</h4>
          </header>
          <main class="col">
            <ul id="list-friends" class="p-0 mt-2">
              {# Отдельный друг #}
              <li class="friend">
                <div class="row d-flex justify-content-start align-items-center">
                  <div class="col-auto">
                    <div class="friend__image">
                      <img src="{{ user_profile_image.url }}" alt="" class="rounded-circle">
                    </div>
                  </div>
                  <div class="col-auto">
                    <h5 class="friend__name">Елена Красавина</h5>
                  </div>
                </div>
              </li>
            </ul>
          </main>
          <footer>
            <a id="show-more-friends" href="#">Показать всех</a>
          </footer>
        </section>
      </div>

      {# Создание поста #}
      {% if request.user.id == user_id %}
        <div class="col-12 col-lg-8 mx-1 mx-md-2">
          <form method="post" enctype="multipart/form-data" class="position-relative">
            {% csrf_token %}
            {{ post_form }}
            <i id="create-post__select-image-icon" class="fa-duotone fa-camera" title="Добавить фото"></i>

            <button type="submit" id="create-post__publish-button" title="Опубликовать">
              <i class="fa-solid fa-paper-plane-top"></i>
            </button>

            <div class="mt-2 position-relative d-inline-block">
              <img src="" alt="" class="preview-image">
              <button type="button" class="d-none delete-uploaded-image-button" data-filename="" title="Удалить">
                <i class="fa-regular fa-xmark"></i>
              </button>
            </div>
            {{ post_form.errors }}
          </form>
        </div>
      {% endif %}

      {# Посты пользователя #}
      {% if user_posts %}
        <div class="col-12 col-lg-8 d-flex justify-content-center">
          <section id="posts" class="row flex-column mx-2 my-4">
            {% for post in user_posts %}
              <div class="col mb-3 p-0 post hover-scale">

                <div class="post__text-info mx-2 my-1">
                  <div class="post__time">
                    <p>{{ post.created|post_date_format }}</p>
                  </div>

                  {% if post.text %}
                    <div class="post__text">
                      <p>{{ post.text }}</p>
                    </div>
                  {% endif %}
                </div>

                {% if post.image %}
                  <div class="post__image">
                    <img src="{{ post.image.url }}" alt="Фото поста" class="img-fluid">
                  </div>
                {% endif %}
              </div>
            {% endfor %}
          </section>
        </div>
      {% else %}
        <div class="row text-center mt-3">
          <div class="col">Постов нет</div>
        </div>
      {% endif %}
    </div>
  </section>

  {# Модальное окно редактирования профиля #}
  <div class="modal fade text-white" id="editProfileModal" tabindex="-1" aria-labelledby="exampleModalLabel"
       aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content bg-dark">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Редактирование профиля</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
          </div>
          <div class="modal-body">
            {{ edit_profile_form.as_div }}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
            <button type="submit" class="btn btn-primary">Сохранить изменения</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}